### ISSUE TITLE
Event.prototype.serialize(plain) - single replace of NL with %0A breaks Content-Length

### ISSUE THREAD

**Issue by mhmeadows63** [englercj/node-esl#63]
The `Content-Length` header is calculated before the first `\n` only is replaced with `%0A`.

Apart from the `content-length` then being wrong, is this `replace` strictly necessary?

In my case, this body:
&nbsp;&nbsp;&nbsp;&nbsp;`<ATM>\n\t<version>1.5</version>\n\t<data>00000</data>\n</ATM>`
becomes:
&nbsp;&nbsp;&nbsp;&nbsp;`<ATM>%0A\t<version>1.5</version>\n\t<data>00000</data>\n</ATM>`
which is nonsense to the recipient.

**Comment by englercj** [comment]
The content-length being calculated too early is certainly a bug. As for the replace, at first I thought the issue was just that it didn't replace them all (i.e. it should be: `.replace(/\n/g, '%0A')`. However, reading back through this code (it has been years since I worked on it) it seems like it is not needed.

So the fixes would likely be to calculate content-lengths properly for each of the types as well as not doing that replace on the body.

**Comment by mhmeadows63** [comment]
I'm agree that the plain-mode replace should be removed.

The json-mode calculation looks fine because the stringify wraps the while event, not just the body.

As for the xml-mode calculation, there may be a need for htmlentity encoding before taking the length, however, I'm not clear on the intended use case.

**Comment by englercj** [comment]
The content length is necessary since it tells you how many bytes of the stream to read for the body. Without that you wouldn't know how many bytes to parse for the message, and would have to do contextual parsing (which this lib and fsw don't do).

Since Content-Length is the byte-length of the body to be read form the stream, it should be calculated after the body is completely encoded.

**Comment by englercj** [comment]
Just published v1.1.9 of `modesl`. Hopefully that fixes your issue!

**Comment by mhmeadows63** [comment]
Just reviewed your 1.1.9 changes:

In xml-mode you have omitted to test whether a body is present to encode.

Also, in plain-mode, you have left the comment that talks of urlencoding NLs

**Comment by englercj** [comment]
Xml does check if the body exist, just under the comment that says "add body". The encode xml returns empty string if passed an empty body so need to check twice. 

I should remove that comment t at some point, but is the change working for you?

**Comment by mhmeadows63** [comment]
I can confirm that the change _is_ working for me.

Many thanks.
